### ISSUE TITLE
backtest results are incomplete, and no orders sent

### ISSUE THREAD

**Issue by djwatt3** [fugle-dev/fugle-backtest-node#2]
Hello,
I'm trying to backtest my strategies with this package and SmaCross included strategy, but the results are incomplete.

I fetch the candle OHLCV from binance with cctx and save in candle[] object
my data is: 
```javascript
[
{"date":"2021-4-7","open":56393.68,"high":58650,"low":55241.63,"close":57314.75,"volume":74543},
....,
{"date":"2021-7-14","open":47799.99,"high":48144,"low":45971.03,"close":47068.51,"volume":46114}
]
``` 

I got these result table:

```
╔════════════════════════╤═══════════════════════╗
║ Strategy               │ SmaCross(n1=20,n2=60) ║
╟────────────────────────┼───────────────────────╢
║ Start                  │ null                  ║
╟────────────────────────┼───────────────────────╢
║ End                    │ null                  ║
╟────────────────────────┼───────────────────────╢
║ Duration               │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Exposure Time [%]      │ 0                     ║
╟────────────────────────┼───────────────────────╢
║ Equity Final [$]       │ 1000000               ║
╟────────────────────────┼───────────────────────╢
║ Equity Peak [$]        │ 1000000               ║
╟────────────────────────┼───────────────────────╢
║ Return [%]             │ 0                     ║
╟────────────────────────┼───────────────────────╢
║ Buy & Hold Return [%]  │ -17.132571            ║
╟────────────────────────┼───────────────────────╢
║ Return (Ann.) [%]      │ 0                     ║
╟────────────────────────┼───────────────────────╢
║ Volatility (Ann.) [%]  │ 0                     ║
╟────────────────────────┼───────────────────────╢
║ Sharpe Ratio           │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Sortino Ratio          │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Calmar Ratio           │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Max. Drawdown [%]      │ 0                     ║
╟────────────────────────┼───────────────────────╢
║ Avg. Drawdown [%]      │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Max. Drawdown Duration │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Avg. Drawdown Duration │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ # Trades               │ 0                     ║
╟────────────────────────┼───────────────────────╢
║ Win Rate [%]           │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Best Trade [%]         │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Worst Trade [%]        │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Avg. Trade [%]         │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Max. Trade Duration    │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Avg. Trade Duration    │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Profit Factor          │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ Expectancy [%]         │ NaN                   ║
╟────────────────────────┼───────────────────────╢
║ SQN                    │ NaN                   ║
╚════════════════════════╧═══════════════════════╝
``` 

furthermore can I test smaller TF like 15minute? if yes how can refactor the date string?
Thanks

**Comment by djwatt3** [comment]
Solved the table result, it's sufficient to increase cash value or change asset, because BTC has high value and the package don't support fractional buy/sell.

instead regarding the backtesting of TF < 1D I get this error:

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Series.mean (C:\Users\******\workspace\Trading\fugle-backtesting\node_modules\danfojs-node\dist\danfojs-base\core\series.js:398:24)
    at Stats.compute (C:\Users\******\workspace\Trading\fugle-backtesting\node_modules\@fugle\backtest\lib\stats.js:92:64)
    at Backtest.run (C:\Users\******\workspace\Trading\fugle-backtesting\node_modules\@fugle\backtest\lib\backtest.js:82:143)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
``` 

with this content data file
```
[
{"date":"2020-05-09 14:45:00","open":0.21988,"high":0.22035,"low":0.2198,"close":0.21989,"volume":396970},
.........
{"date":"2020-05-14 19:30:00","open":0.20163,"high":0.20163,"low":0.20025,"close":0.20077,"volume":1513820}
]
``` 

Can you help me about it? I trying to test my strategies on low TF like 5,15,30 minutes.
Thanks

**Comment by chunkai1312** [comment]
Hi @djwatt3, you can try converting the `date` field in the historical data to the ISO 8601 format, like this:

```
2020-05-09 14:45:00 ---> 2020-05-09T14:45:00Z
2020-05-14 19:30:00 ---> 2020-05-14T19:30:00Z
```
Then run the backtest again and see if it works.

**Comment by djwatt3** [comment]
Hi @chunkai1312 
your solution seems to work properly
Thanks
